# Generated by Django 4.1.2 on 2024-07-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('Rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Vehiculo', models.CharField(max_length=6)),
                ('Via_de_circulacion', models.CharField(max_length=50)),
                ('tipo_de_infraccion', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('Monto', models.CharField(max_length=45)),
                ('rut2', models.CharField(max_length=10)),
                ('Rol_inspector', models.CharField(blank=True, max_length=50, null=True)),
                ('Descripcion_infraccion', models.CharField(max_length=50)),
                ('Datos_sensor', models.CharField(max_length=50)),
            ],
        ),
    ]
